import { useEffect, useState } from "react";

const PHRASES: Record<string, string[]> = {
  general: [
    "marinating on that... 🍖",
    "letting it simmer... 🍲",
    "preheating the brain... 🔥",
    "seasoning the response... 🧂",
    "slow cooking an answer... 🐢",
    "whisking it together... 🥄",
    "folding in the context... 📄",
    "reducing the codebase... 🧠",
    "deglazing with tokens... ✨",
    "plating the thoughts... 🍽️",
    // new additions
    "blending the chaos... 🌀",
    "tasting the logic... 👅",
    "kneading the ideas... 🥖",
    "sautéing thoughts... 🍳",
    "folding in extra brainpower... 🧠",
    "caramelizing the mistakes... 🍯",
    "letting it chill... ❄️",
    "flambéing the bugs... 🔥",
    "mixing code and chaos... 🥣",
    "plating the hot take... 🔥🍽️",
    "simmering existential dread... 🫠",
    "tempering the output... ⚡",
    "basting with logic... 🧂",
    "drizzling insight... 🌧️",
    "sprinkling genius... ✨",
    "slow roasting complexity... 🐢🔥",
    "blending the universe... 🌌",
    "whipping up brilliance... 🥄💡",
    "folding in main character energy... 🌟",
    "checking internal temperatures... 🌡️",
  ],

  cloning: [
    "cloning at the speed of git... 🚀",
    "negotiating with github... 🤝",
    "untangling the object graph... 🧶",
    "counting commits like sheep... 🐑",
    "shallow clone, deep thoughts... 🌊",
    "fetching the whole iceberg... 🧊",
    "packing objects... 📦",
    "resolving deltas... 🔄",
    "checking out the vibes... 😎",
    "recursing into submodules... 🔁",
    "buffering the bits... 💾",
    "git is being git... 🤷",
    "praying to the network gods... 🙏",
    "downloading the internet (just your repo)... 🌐",
    // new additions
    "forking in style... 🍴",
    "pulling commits aggressively... 🏃‍♂️",
    "syncing the vibes... 🌊",
    "deep cloning existential crises... 😵",
    "cherry-picking brilliance... 🍒",
    "rewriting history (just a little)... 📝",
    "fast-forwarding thoughts... ⏩",
    "merging with the multiverse... 🌌",
    "rebasing reality... 🔄",
    "checking out chaos... 😎",
    "cloning like a pro... 👑",
    "replicating the vibes... 🔁",
    "buffer overflow in progress... 💾",
    "pull request to sanity... 🤯",
    "diverging the timeline... ⏳",
    "squashing git guilt... 🪓",
    "fetching inspiration... 📡",
    "pruning branches... 🌿",
    "syncing neurons... 🧠",
    "shallow clone, deep existential dread... 🌊😵",
  ],

  analyzing: [
    "reading every file (skimming)... 📖",
    "building a mental model... 🧠",
    "reverse engineering intent... 🔍",
    "parsing the chaos... 🌀",
    "connecting the dots... 🔗",
    "finding the load-bearing files... 🏗️",
    "mapping the dependency graph... 🗺️",
    "absorbing the architecture... 🧱",
    "noticing things... 👀",
    "judging your folder structure... 😭",
    "appreciating the tech debt... 💳",
    "counting your TODOs... 📋",
    "reading between the lines... ✍️",
    "anthropic-ifying your codebase... 🤖",
    "following the import trail... 🧭",
    "speed-reading your life's work... ⚡",
    "pretending to understand your monorepo... 🏢",
    // new additions
    "debugging the cosmos... 🌌",
    "profiling your thoughts... 📊",
    "mapping mental threads... 🧵",
    "sifting through the noise... 🌪️",
    "predicting your next move... 🔮",
    "annotating life... ✍️",
    "absorbing the vibes... 🧘",
    "peering into recursion... 🔁",
    "modeling chaos... 🧩",
    "counting edge cases... ⚠️",
    "tracking call stacks... 🧗",
    "parsing your aura... 🌈",
    "reading the README of life... 📖",
    "analyzing existential types... 🤯",
    "observing folder hierarchies... 📂",
    "profiling main character energy... 🎬",
    "absorbing every commit... 💾",
    "studying the architecture... 🏛️",
    "checking for ghost functions... 👻",
    "validating vibes... ✅",
  ],

  model: [
    "deciding which files matter... 🧠",
    "picking the important ones... 🎯",
    "triaging your codebase... 🚑",
    "figuring out where to look... 👀",
    "consulting the file oracle... 🔮",
    "narrowing it down... 🔍",
    "skimming the directory... 📂",
    "choosing wisely... 🧠",
    "not reading everything (smart)... 😎",
    "filtering the noise... 🔇",
    "asking the oracle... 🔮",
    "pinging the motherbrain... 🧠",
    "waiting on the neurons... ⏳",
    "tokens incoming... 📥",
    "model is cooking... 🍳",
    "inference in progress... ⚙️",
    "the GPU is thinking... 💻",
    "attention is all we need... 🎯",
    "cross-attending to your vibes... 🔄",
    "softmaxing the options... 📊",
    "sampling from the distribution... 🎲",
    "temperature: just right... 🌡️",
    "context window: not full yet... 🪟",
    "next token any second now... ⏳",
    "beaming thoughts from the datacenter... 📡",
    "anthropic servers sweating... 💦",
    "matrix multiply in progress... ➗",
    // new additions
    "initializing hype mode... 🚀",
    "compiling neurons... 🧠",
    "loading chaotic energy... ⚡",
    "predicting your mood... 😏",
    "sampling absurdity... 🎲",
    "normalizing brainwaves... 🌊",
    "cross-validating genius... 🧪",
    "activating main character module... 🎬",
    "warming up GPU... 💻🔥",
    "spooling synapses... 🧵",
    "calculating cringe factor... 🤡",
    "preprocessing drama... 📦",
    "injecting chaos vectors... ⚡",
    "softmaxing life choices... 🧠",
    "attention heads online... 👀",
    "broadcasting vibes... 📡",
    "loading meme embeddings... 🗿",
    "quantizing mood... 🔢",
    "clipping gradients of patience... ✂️",
    "inferring main plot points... 📖",
  ],

  summary: [
    "synthesizing the chaos... 🧠",
    "forming an opinion... 💭",
    "writing the verdict... 📝",
    "digesting everything... 🍽️",
    "putting it all together... 🧩",
    "crafting the overview... ✨",
    "making sense of it all... 🤔",
    "distilling the essence... 🧪",
    "summarizing your life's work... 📚",
    "turning files into feelings... 💔",
    "extracting signal from noise... 📡",
    "generating hot takes... 🔥",
    "cooking up the analysis... 🍳",
    "almost done judging your code... 👀",
    "writing the report card... 📊",
    // new additions
    "digesting chaos into art... 🎨",
    "compressing existential dread... 🫠",
    "executing life summary... 📝",
    "extracting hot takes... 🔥",
    "packaging thoughts nicely... 📦",
    "synthesizing main character energy... 🌟",
    "boiling down code spaghetti... 🍝",
    "condensing into brilliance... ✨",
    "drawing the final diagram... 📊",
    "reporting on universal logic... 🌌",
    "giving verdict with style... 😎",
    "folding in chaos gracefully... 🌀",
    "capturing essence... 📸",
    "writing the epic conclusion... 📜",
    "connecting all dots... 🔗",
    "rendering summary in HD... 📺",
    "wrapping thoughts in elegance... 🎁",
    "making insights bussin... 🥵",
    "compressing noise... 🔇",
    "finishing the mental buffet... 🍽️",
  ],

  task: [
    "thinking about your ask... 🤔",
    "processing the request... ⚙️",
    "on it... 🫡",
    "got it, working... 💻",
    "considering the angles... 🔺",
    "thinking this through... 🧠",
    "working on it... 🔧",
    "cooking up a plan... 🍳",
    "breaking it down... 🧩",
    "figuring out the approach... 🧭",
    "strategizing... 📊",
    "mapping out the steps... 🗺️",
    "scoping the work... 📏",
    "locking in... 🔒",
    "challenge accepted... ⚔️",
    // new additions
    "igniting the thinking engines... 🔥",
    "prioritizing chaos... 📝",
    "breaking down mental blocks... 🧱",
    "assembling the mental toolkit... 🛠️",
    "deploying logic... 🚀",
    "strategizing with style... 💅",
    "mapping the mental maze... 🗺️",
    "executing plan... ⚙️",
    "optimizing approach... 🧠",
    "thinking outside the semicolon... ;",
    "iterating on brilliance... 🔄",
    "analyzing all angles... 🔺",
    "tracking progress... 📊",
    "debugging plan... 🐞",
    "brainstorming in HD... 💭",
    "navigating chaos... 🧭",
    "forming master plan... 🏗️",
    "locking in focus... 🔒",
    "assembling neural units... 🧩",
    "finalizing strategy... ✅",
  ],

  commit: [
    "sniffing the diff... 👃",
    "reading your crimes... 😭",
    "git add -A (the audacity)... 😤",
    "crafting the perfect lie^H^H^H message... 📝",
    "summoning commit message energy... ✨",
    "writing words that will haunt the git log... 👻",
    "pretending this was intentional all along... 😎",
    "making it sound like a feature... 🚀",
    "staging your changes (and your career)... 📦",
    "turning chaos into conventional commits... 🧠",
    "making history. literally... 📜",
    "git blame: not it... 🫣",
    "this commit brought to you by AI... 🤖",
    "imperative mood activated... ⚡",
    "72 chars or bust... 📏",
    "no WIP commits on my watch... 🚫",
    "writing the commit future-you will thank me for... 🙏",
    "touching the object store... 🗄️",
    "packing your changes real tight... 📦",
    "signing off mentally... 🧠",
    "squash? no. this one deserves to live... 🧬",
    "git log will remember this... 📖",
    "diffing the vibe before committing... 🔍",
    "committing to the bit. and also the repo... 💾",
    "generating a message with zero typos (probably)... 😅",
    "making main proud... 🏆",
    // new additions
    "annotating history with chaos... 📝",
    "staging brilliance... 🌟",
    "blaming the compiler... 🤖",
    "git commit -m 'oops'... 😅",
    "crafting legendary messages... 🏆",
    "squashing typos... ✂️",
    "documenting chaos... 📜",
    "ghostwriting commit energy... 👻",
    "pushing existential code... 🚀",
    "reviewing self-inflicted bugs... 😭",
    "summoning git spirits... 👻",
    "committing main character vibes... 🎬",
    "annotating universal truths... 🌌",
    "logging brain activity... 🧠",
    "staging memes... 🗿",
    "locking in brilliance... 🔒",
    "quantifying audacity... 😤",
    "making history, one commit at a time... 📖",
    "git blame: me again... 😎",
    "finalizing legendary diff... ✨",
  ],
};

function pick(list: string[], lastIndex: number): number {
  let next = Math.floor(Math.random() * list.length);
  if (next === lastIndex) next = (next + 1) % list.length;
  return next;
}

export type ThinkingKind = keyof typeof PHRASES;

export function useThinkingPhrase(
  active: boolean,
  kind: ThinkingKind = "general",
  intervalMs = 4321,
): string {
  const list = PHRASES[kind]!;
  const [index, setIndex] = useState(() =>
    Math.floor(Math.random() * list.length),
  );

  useEffect(() => {
    if (!active) return;
    setIndex((i) => pick(list, i));
    const id = setInterval(() => setIndex((i) => pick(list, i)), intervalMs);
    return () => clearInterval(id);
  }, [active, kind, intervalMs]);

  return list[index]!;
}
